name: "Analyze code"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Try publish package"
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: "{}"
          dryRunOnly: true
          flutter: true
          force: true
          skipTests: true
          accessToken:
          refreshToken:

  test_android:
    needs: analyze
    name: Test Android build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk --debug
        working-directory: example

  test_darwin:
    needs: analyze
    name: Test iOS build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build ios --no-codesign
        working-directory: example