name: Publish to pub.dev

on:
  release:
    types: 
      - created
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Publish to pub.dev'
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          dryRunOnly: false
          flutter: true
          force: true
          skipTests: true
          accessToken: 
          refreshToken: 